import { Vector2 } from "../math/";
import { GameOptions } from "./game-options";
import { Scene } from "./scene";
export declare class Game {
    private static _instance;
    private static _launched;
    private _time;
    private _keyboard;
    private _mouse;
    private _renderer;
    private _canvas;
    private _scene;
    private _size;
    private _shouldResize;
    private constructor();
    static get focused(): boolean;
    static get canvas(): HTMLCanvasElement;
    static get scene(): Scene;
    static set scene(scene: Scene);
    static get width(): number;
    static get height(): number;
    static get size(): Vector2;
    static get screenWidth(): number;
    static get screenHeight(): number;
    static get screenSize(): Vector2;
    static get scaleFactor(): number;
    static launch(options: GameOptions): void;
    private static get _self();
    private static _ensureNotLaunched;
    private static _ensureLaunched;
    private _launch;
    private _initialize;
    private _initializeCanvas;
    private _start;
    private _update;
    private _nextFrame;
    private _frame;
    private _handleResizing;
    private _resizeCanvas;
}
