name: Build

on:
  push:
    branches:
      - master

jobs:
  build-and-commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run format

      - name: Build
        run: npm run build

      - name: Commit build output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build
          git commit -m "Update build [skip ci]" || echo "No changes to commit"
          git push
